### ISSUE TITLE
Compatability for Customizer's Galaxy Theme

### ISSUE THREAD

**Issue by Ryonez** [kenlog/MinimizeSidebar#1]
Hey, I'd like to request the plugin for fit in with the Galaxy theme that's part of Customizer a bit better please.

Currently it's a bright green color:
![image](https://user-images.githubusercontent.com/16157130/60136130-78264100-97f7-11e9-802e-d6d7837654e7.png)

And when highlighted it turns white:
![image](https://user-images.githubusercontent.com/16157130/60136155-86745d00-97f7-11e9-8904-166947a59949.png)

It'd be a bit nicer on my eyes if it used the gray used throughout the theme.

**Comment by kenlog** [comment]
The color is not defined in this plugin, in this way the color is taken from the theme in use, in this case I assume that the theme you are using has the color of the green buttons.

**Comment by Ryonez** [comment]
The buttons are indeed green.

Would you mind looking to see if it's feasible to customize the colors, maybe when you look at #2?

**Comment by kenlog** [comment]
if it will be possible in the next versions I will do it.
