### ISSUE TITLE
Doesn't Remember Last State

### ISSUE THREAD

**Issue by Ryonez** [kenlog/MinimizeSidebar#2]
Sometimes when working it's convenient to have the sidebar left out. Currently, the sidebar is collapsed whenever the page is reloaded or changed.

It'd be beneficial for the sidebar to remember the last state so time isn't wasted by constantly having to open it.

**Comment by kenlog** [comment]
Surely I will implement this in the next version.

**Comment by xypd** [comment]
Has there been any updates on this? This is a very nice little plugin. However when you're editing a task it can be inconvenient to reopen after every sidebar menu action click, enough so that I may need to remove it. 

Thanks for all your work on Kanboard in general!
